### ISSUE TITLE
New version planned?

### ISSUE THREAD

**Issue by Magnus-101** [sormy/gentoo-quick-installer#2]
Hello, do you plan to update the script? I installed it but I think it fails when installing grub everything seems to be fine but then the system boots directly without grub menu, after installation I installed grub again according to the Gentoo wiki and it sends me to grub rescue ... maybe some bug, thanks for the work.  ; D

**Comment by sormy** [comment]
Thanks for report. I will fix the script. If you know what is wrong, then feel free to submit PR.

**Comment by Magnus-101** [comment]
Ok no problem, i'll wait for the fix, thanks for the work  (i use BIOS btw)
